package hoteles.model;
// Generated 10/06/2013 06:00:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Estadohabitacion generated by hbm2java
 */
public class Estadohabitacion  implements java.io.Serializable {


     private Integer idEstadoHabitacion;
     private String nombre;
     private String descripcion;
     private Set habitacionxhotels = new HashSet(0);

    public Estadohabitacion() {
    }

	
    public Estadohabitacion(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Estadohabitacion(String nombre, String descripcion, Set habitacionxhotels) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.habitacionxhotels = habitacionxhotels;
    }
   
    public Integer getIdEstadoHabitacion() {
        return this.idEstadoHabitacion;
    }
    
    public void setIdEstadoHabitacion(Integer idEstadoHabitacion) {
        this.idEstadoHabitacion = idEstadoHabitacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getHabitacionxhotels() {
        return this.habitacionxhotels;
    }
    
    public void setHabitacionxhotels(Set habitacionxhotels) {
        this.habitacionxhotels = habitacionxhotels;
    }




}


