package hoteles.model;
// Generated 10/06/2013 06:00:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Estancia generated by hbm2java
 */
public class Estancia  implements java.io.Serializable {


     private Integer id;
     private Habitacionxhotel habitacionxhotel;
     private Reserva reserva;
     private int idReservacion;
     private Date fechaInicio;
     private Date fechaFinal;

    public Estancia() {
    }

	
    public Estancia(Habitacionxhotel habitacionxhotel, Reserva reserva, int idReservacion, Date fechaInicio) {
        this.habitacionxhotel = habitacionxhotel;
        this.reserva = reserva;
        this.idReservacion = idReservacion;
        this.fechaInicio = fechaInicio;
    }
    public Estancia(Habitacionxhotel habitacionxhotel, Reserva reserva, int idReservacion, Date fechaInicio, Date fechaFinal) {
       this.habitacionxhotel = habitacionxhotel;
       this.reserva = reserva;
       this.idReservacion = idReservacion;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Habitacionxhotel getHabitacionxhotel() {
        return this.habitacionxhotel;
    }
    
    public void setHabitacionxhotel(Habitacionxhotel habitacionxhotel) {
        this.habitacionxhotel = habitacionxhotel;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public int getIdReservacion() {
        return this.idReservacion;
    }
    
    public void setIdReservacion(int idReservacion) {
        this.idReservacion = idReservacion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }




}


