package hoteles.model;
// Generated 10/06/2013 06:00:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Habitacionxhotel generated by hbm2java
 */
public class Habitacionxhotel  implements java.io.Serializable {


     private Integer idHabitacion;
     private Estadohabitacion estadohabitacion;
     private Tipohabitacion tipohabitacion;
     private Hoteles hoteles;
     private int numeroHabitacion;
     private Set suplementoses = new HashSet(0);
     private Set estancias = new HashSet(0);

    public Habitacionxhotel() {
    }

	
    public Habitacionxhotel(Estadohabitacion estadohabitacion, Tipohabitacion tipohabitacion, Hoteles hoteles, int numeroHabitacion) {
        this.estadohabitacion = estadohabitacion;
        this.tipohabitacion = tipohabitacion;
        this.hoteles = hoteles;
        this.numeroHabitacion = numeroHabitacion;
    }
    public Habitacionxhotel(Estadohabitacion estadohabitacion, Tipohabitacion tipohabitacion, Hoteles hoteles, int numeroHabitacion, Set suplementoses, Set estancias) {
       this.estadohabitacion = estadohabitacion;
       this.tipohabitacion = tipohabitacion;
       this.hoteles = hoteles;
       this.numeroHabitacion = numeroHabitacion;
       this.suplementoses = suplementoses;
       this.estancias = estancias;
    }
   
    public Integer getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(Integer idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Estadohabitacion getEstadohabitacion() {
        return this.estadohabitacion;
    }
    
    public void setEstadohabitacion(Estadohabitacion estadohabitacion) {
        this.estadohabitacion = estadohabitacion;
    }
    public Tipohabitacion getTipohabitacion() {
        return this.tipohabitacion;
    }
    
    public void setTipohabitacion(Tipohabitacion tipohabitacion) {
        this.tipohabitacion = tipohabitacion;
    }
    public Hoteles getHoteles() {
        return this.hoteles;
    }
    
    public void setHoteles(Hoteles hoteles) {
        this.hoteles = hoteles;
    }
    public int getNumeroHabitacion() {
        return this.numeroHabitacion;
    }
    
    public void setNumeroHabitacion(int numeroHabitacion) {
        this.numeroHabitacion = numeroHabitacion;
    }
    public Set getSuplementoses() {
        return this.suplementoses;
    }
    
    public void setSuplementoses(Set suplementoses) {
        this.suplementoses = suplementoses;
    }
    public Set getEstancias() {
        return this.estancias;
    }
    
    public void setEstancias(Set estancias) {
        this.estancias = estancias;
    }




}


