package hoteles.model;
// Generated 10/06/2013 06:00:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hoteles generated by hbm2java
 */
public class Hoteles  implements java.io.Serializable {


     private Integer idHotel;
     private String nombre;
     private String ubicacion;
     private Set reservas = new HashSet(0);
     private Set habitacionxhotels = new HashSet(0);
     private Set empleadoses = new HashSet(0);

    public Hoteles() {
    }

	
    public Hoteles(String nombre, String ubicacion) {
        this.nombre = nombre;
        this.ubicacion = ubicacion;
    }
    public Hoteles(String nombre, String ubicacion, Set reservas, Set habitacionxhotels, Set empleadoses) {
       this.nombre = nombre;
       this.ubicacion = ubicacion;
       this.reservas = reservas;
       this.habitacionxhotels = habitacionxhotels;
       this.empleadoses = empleadoses;
    }
   
    public Integer getIdHotel() {
        return this.idHotel;
    }
    
    public void setIdHotel(Integer idHotel) {
        this.idHotel = idHotel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getHabitacionxhotels() {
        return this.habitacionxhotels;
    }
    
    public void setHabitacionxhotels(Set habitacionxhotels) {
        this.habitacionxhotels = habitacionxhotels;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


