package hoteles.model;
// Generated 10/06/2013 06:00:09 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idReserva;
     private Clientes clientes;
     private Empleados empleados;
     private Hoteles hoteles;
     private int idHabitacion;
     private Date tiempoEntrada;
     private Date tiempoSalida;
     private double adelanto;
     private Set facturas = new HashSet(0);
     private Set estancias = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(Clientes clientes, Empleados empleados, Hoteles hoteles, int idHabitacion, Date tiempoEntrada, Date tiempoSalida, double adelanto) {
        this.clientes = clientes;
        this.empleados = empleados;
        this.hoteles = hoteles;
        this.idHabitacion = idHabitacion;
        this.tiempoEntrada = tiempoEntrada;
        this.tiempoSalida = tiempoSalida;
        this.adelanto = adelanto;
    }
    public Reserva(Clientes clientes, Empleados empleados, Hoteles hoteles, int idHabitacion, Date tiempoEntrada, Date tiempoSalida, double adelanto, Set facturas, Set estancias) {
       this.clientes = clientes;
       this.empleados = empleados;
       this.hoteles = hoteles;
       this.idHabitacion = idHabitacion;
       this.tiempoEntrada = tiempoEntrada;
       this.tiempoSalida = tiempoSalida;
       this.adelanto = adelanto;
       this.facturas = facturas;
       this.estancias = estancias;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public Hoteles getHoteles() {
        return this.hoteles;
    }
    
    public void setHoteles(Hoteles hoteles) {
        this.hoteles = hoteles;
    }
    public int getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(int idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Date getTiempoEntrada() {
        return this.tiempoEntrada;
    }
    
    public void setTiempoEntrada(Date tiempoEntrada) {
        this.tiempoEntrada = tiempoEntrada;
    }
    public Date getTiempoSalida() {
        return this.tiempoSalida;
    }
    
    public void setTiempoSalida(Date tiempoSalida) {
        this.tiempoSalida = tiempoSalida;
    }
    public double getAdelanto() {
        return this.adelanto;
    }
    
    public void setAdelanto(double adelanto) {
        this.adelanto = adelanto;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getEstancias() {
        return this.estancias;
    }
    
    public void setEstancias(Set estancias) {
        this.estancias = estancias;
    }




}


