package hoteles.model;
// Generated 10/06/2013 06:00:09 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Suplementos generated by hbm2java
 */
public class Suplementos  implements java.io.Serializable {


     private Integer idSuplementos;
     private String nombre;
     private String descripcion;
     private double precio;
     private Set habitacionxhotels = new HashSet(0);

    public Suplementos() {
    }

	
    public Suplementos(String nombre, String descripcion, double precio) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precio = precio;
    }
    public Suplementos(String nombre, String descripcion, double precio, Set habitacionxhotels) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.habitacionxhotels = habitacionxhotels;
    }
   
    public Integer getIdSuplementos() {
        return this.idSuplementos;
    }
    
    public void setIdSuplementos(Integer idSuplementos) {
        this.idSuplementos = idSuplementos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Set getHabitacionxhotels() {
        return this.habitacionxhotels;
    }
    
    public void setHabitacionxhotels(Set habitacionxhotels) {
        this.habitacionxhotels = habitacionxhotels;
    }




}


